### ISSUE TITLE
docs: "Tips and tricks" section?

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/flir#90]
Used the following while working on #83 to easily replace `expect_error()` by `expect_snapshot()`:

* `snapshot.yml`:

```yml
id: snapshot
language: r
severity: warning
rule:
  pattern: expect_error($CODE, $$$)
fix: |
  expect_snapshot(
    ~~CODE~~,
    error = TRUE
  )
message: ...
```

```r
fix_dir("tests", linters = "/home/etienne/Desktop/Git/flir/snapshot.yml")
```

---

Might be useful to list this kind of examples somewhere?
